language: node_js
node_js:
  - node
  - "8"
dist: trusty
before_install:
  - rm -rf node_modules
  - npm i -g babel-cli webpack truffle-contract
after_success:
  - |
    if [ ${TRAVIS_BRANCH} = "master" ]; then
      export NODE_ENV=production;
    else
      export NODE_ENV=development;
    fi
  - npm run build
deploy:
  - provider: s3
    bucket: management-development
    secret_access_key:
      secure: a71Dgcrc7/anHWw2sW2NXzJRJum5lYvrybcC5kiMEzb2TJQlVKAxti93zTpNZ2J4sxHrbopHhn687Z2svzy3AFhZDG1qCOIMgHFNwG4G0gnUG9mi86OB/l0mM2pdt6fHN1bXQeIzexwHGkh7jmUF8OLHLm46FYJxgSdz/Hla4GJv+2mKmREqOWwHRXnfoB2nYY5p5RxmgDaSU0WYd9R43vIjM5OMsoUmnl9Itw0dSUHtR7igJcsGE4IXfK3nlULwBitybU9VrH3G9XJmxQjiVskKz39zHhTlsF8sFR78dtatOCzF9IDYM1euxQCL5V9ZDYmz+iMq6iD/srODWhF4EAI6j5kfm4oRWAw09bPZT2AoBFNIMoVijYy6r9WHd2F/R5ICBBlX3fdTR5xUySHE5vZCMnQkqNAz3iQfQ9zagycfRvMHk5EylomoCibqN9i+bqsu8YaLksglH0lfdtrPO9N0hSQJ8aeqTrOHXv//cg6O+W/AK8BsGVRFk6runxQqbVBPy9RP4uwMtM7sErLHEm5oYTlsUhLn7nWn6yOHpcQbW5L2/BKTS4nm47U6QglYAIPgTQPSXeEElNJ4RSYwdxbJFKvLRhNAeCdBzIb6PVxjeTdmYqo0owjZpQUi7filZtQ2HEAG/QVbrr6qvGBlfxS7phAeIbpObGE4w3uLbvM=
    access_key_id:
      secure: bPyA4qz/PVCHZbXCjWBkmRAaIyLpWIL4TSFIwukE/v9vmJYSdaCej4QUjgEf1D81lVKjsNU9OLnmIuhSDjTTVLXGf7njPJx9w2I66vqVauwQLxqDGq/7k0Cm+y/HFUBFWSlLfovUuHBrz4cv94CxlWeD06zm8Tb8Fz1lhAE0vDftYdeFOzx2V9IvDSL6/nDWCa+hpwvcaN9vMTGiWBFBAqMdwWSDLml4kTs6VMb5HtX0pFL0SQU62M+VkMCZYsI5XU8+JNjvzm+iGSlHSnR/iMeRYFodilBs93Emvc018vtJcSBRY12mh9zWkSx4+ZrZERv9hFtj3NE/HstxnbOnGbZH6vLdotn7VSbJxLx3BlHxJXmSy67TFF7HBuAOJOm0tQRnINQD631j0PN1+2BGNRPHy42Iftp4t7YbCpMI32tnbnnLial3TLiv1pNdfqbVf6VmQEb3U098ESQC5ZiQWG+iLH8w31Ypm645dd0eSrU30l/rUmmDMaxtV+jFLQbHmBON+sUCycr2qGt9DiX8EuSHKni17W1Qg6QkgEf8xwkoe3tWu4+J/JtdyxOGXsoDPRue+vbUTSzzJMdyTTCFNagGufy6idMjbXggG2EDRfhV9zdR+a0+Y0MKelSltm5vBoDJokaBi95PgujCe8wWNJhRmHAOvL2wbfoGtOEW7SA=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: development
  - provider: s3
    bucket: management-staging
    secret_access_key:
      secure: a71Dgcrc7/anHWw2sW2NXzJRJum5lYvrybcC5kiMEzb2TJQlVKAxti93zTpNZ2J4sxHrbopHhn687Z2svzy3AFhZDG1qCOIMgHFNwG4G0gnUG9mi86OB/l0mM2pdt6fHN1bXQeIzexwHGkh7jmUF8OLHLm46FYJxgSdz/Hla4GJv+2mKmREqOWwHRXnfoB2nYY5p5RxmgDaSU0WYd9R43vIjM5OMsoUmnl9Itw0dSUHtR7igJcsGE4IXfK3nlULwBitybU9VrH3G9XJmxQjiVskKz39zHhTlsF8sFR78dtatOCzF9IDYM1euxQCL5V9ZDYmz+iMq6iD/srODWhF4EAI6j5kfm4oRWAw09bPZT2AoBFNIMoVijYy6r9WHd2F/R5ICBBlX3fdTR5xUySHE5vZCMnQkqNAz3iQfQ9zagycfRvMHk5EylomoCibqN9i+bqsu8YaLksglH0lfdtrPO9N0hSQJ8aeqTrOHXv//cg6O+W/AK8BsGVRFk6runxQqbVBPy9RP4uwMtM7sErLHEm5oYTlsUhLn7nWn6yOHpcQbW5L2/BKTS4nm47U6QglYAIPgTQPSXeEElNJ4RSYwdxbJFKvLRhNAeCdBzIb6PVxjeTdmYqo0owjZpQUi7filZtQ2HEAG/QVbrr6qvGBlfxS7phAeIbpObGE4w3uLbvM=
    access_key_id:
      secure: bPyA4qz/PVCHZbXCjWBkmRAaIyLpWIL4TSFIwukE/v9vmJYSdaCej4QUjgEf1D81lVKjsNU9OLnmIuhSDjTTVLXGf7njPJx9w2I66vqVauwQLxqDGq/7k0Cm+y/HFUBFWSlLfovUuHBrz4cv94CxlWeD06zm8Tb8Fz1lhAE0vDftYdeFOzx2V9IvDSL6/nDWCa+hpwvcaN9vMTGiWBFBAqMdwWSDLml4kTs6VMb5HtX0pFL0SQU62M+VkMCZYsI5XU8+JNjvzm+iGSlHSnR/iMeRYFodilBs93Emvc018vtJcSBRY12mh9zWkSx4+ZrZERv9hFtj3NE/HstxnbOnGbZH6vLdotn7VSbJxLx3BlHxJXmSy67TFF7HBuAOJOm0tQRnINQD631j0PN1+2BGNRPHy42Iftp4t7YbCpMI32tnbnnLial3TLiv1pNdfqbVf6VmQEb3U098ESQC5ZiQWG+iLH8w31Ypm645dd0eSrU30l/rUmmDMaxtV+jFLQbHmBON+sUCycr2qGt9DiX8EuSHKni17W1Qg6QkgEf8xwkoe3tWu4+J/JtdyxOGXsoDPRue+vbUTSzzJMdyTTCFNagGufy6idMjbXggG2EDRfhV9zdR+a0+Y0MKelSltm5vBoDJokaBi95PgujCe8wWNJhRmHAOvL2wbfoGtOEW7SA=
    skip_cleanup: true
    local_dir: dist
    on:
      branch: master
